php artisan make:model category
php artisan make:model feedback
php artisan make:model galery
php artisan make:model orders
php artisan make:model order_details
php artisan make:model product
php artisan make:model role
php artisan make:model tokens
php artisan make:model user
php artisan make:model product_details